# model_list: (it is useful to list all the models configured in litellm proxy)

#   # Ollama Models (self-hosted)
#   - model_name: mistral
#     litellm_params:
#       model: ollama/mistral
#       api_base: http://localhost:11434
  
  
#   # Gemini Models
#   - model_name: gemini-flash
#     litellm_params:
#       model: gemini/gemini-2.5-flash-lite
       
# Note: 
# Gemini models and other API-key based models are managed 
# via the LiteLLM Proxy Admin UI (http://localhost:4000/ui)

  
# General settings
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
